#!/usr/bin/perl 
# Perlbug sqldb datafix updater
# (C) 1999 Richard Foley RFI perlbug@rfi.net 
# $Id: bugfix,v 1.3 2001/04/21 20:48:48 perlbug Exp $
#

=head1 NAME

DATAFIX

=head1 DESCRIPTION

Trawl through the db, looking for incorrect data: correct it, or destroy it :-)

=head1 USAGE

	datafix [object|table]

=cut

use strict;
use vars(qw($VERSION));
$VERSION = do { my @r = (q$Revision: 1.3 $ =~ /\d+/g); sprintf "%d."."%02d" x $#r, @r }; 

use Carp; 
use FindBin;
use lib "$FindBin::Bin/..";
use IO::File;
use Perlbug::Fix;
$|=1;

# DOIT
# -----------------------------------------------------------------------------
my $ok = 1;
my $item  = $ARGV[0] || '';
my $o_fix = Perlbug::Fix->new($item);
$o_fix->cmd; # loop

print "All over -> ok($ok)\n";
$o_fix->clean_up;

exit 0;

