#!/usr/bin/perl 
# Perlbug mail interface to database (bugdb)
# (C) 1999 2000 Richard Foley RFI perlbug@rfi.net 
# $Id: bugmail,v 1.3 2001/02/26 10:04:36 perlbug Exp $
#
use strict;
use vars(qw($VERSION));
$VERSION = do { my @r = (q$Revision: 1.3 $ =~ /\d+/g); sprintf "%d."."%02d" x $#r, @r }; 

use FindBin;
use lib "$FindBin::Bin/..";
use Mail::Internet;
use Perlbug::Interface::Email;
$|=1;

my $mail = Mail::Internet->new(*STDIN);  
my $pb = Perlbug::Interface::Email->new($mail);

my ($h_cmds, $body) = $pb->parse_mail();
my @res = $pb->process_commands($h_cmds, $body);
$pb->return_info($mail, join("\n", @res));
$pb->clean_up("$0 done");

exit(0);
