#!/usr/bin/perl
# Perlbug mail bugtron processor (tron) 
# (C) 1999 2000 Richard Foley RFI perlbug@rfi.net 
# $Id: bugmail,v 1.6 2001/10/22 15:29:51 richardf Exp $
#
use strict;
use vars(qw($VERSION));
$VERSION = do { my @r = (q$Revision: 1.6 $ =~ /\d+/g); sprintf "%d."."%02d" x $#r, @r }; 

use Data::Dumper;
use FindBin;
use lib "$FindBin::Bin/..";
use Mail::Internet;
use Perlbug::Interface::Email;
$|=1;

my $o_int = Mail::Internet->new(\*STDIN);
my $o_email = Perlbug::Interface::Email->new;

my $h_cmds = $o_email->parse_input($o_int);

my @res = $o_email->process_commands($h_cmds, $o_int);

$o_email->clean_up("$0 -> res(@res)");

exit 0;
