#!/usr/bin/perl 
# Perlbug mail bugtron processor (tron) 
# (C) 1999 2000 Richard Foley RFI perlbug@rfi.net 
# $Id: bugtron,v 1.2 2001/02/18 13:55:56 perlbug Exp $
#
use strict;
use vars(qw($VERSION));
$VERSION = do { my @r = (q$Revision: 1.2 $ =~ /\d+/g); sprintf "%d."."%02d" x $#r, @r }; 

use FindBin;
use lib "$FindBin::Bin/..";
use Mail::Internet;
use Perlbug::Interface::Email;
$|=1;

my $mail = Mail::Internet->new(*STDIN);
my $pb = Perlbug::Interface::Email->new($mail);

my ($meth, $msg) = $pb->switch;
my $ok = $pb->$meth($mail); 
$pb->clean_up("$0 meth($meth) -> msg($msg) -> ($ok)");

exit 0;
