#!/usr/bin/perl 
# Perlbug command line interface
# (C) 2000 Richard Foley RFI perlbug@rfi.net 
# $Id: bugdb,v 1.3 2000/06/27 05:49:16 perlbug Exp perlbug $
# 
# 20.06.2000 Initial version
# 

use File::Spec; 
use lib (File::Spec->updir, qw(/home/richard/Live /home/perlbug));
use Mail::Header;
use Perlbug::Cmd;
use strict;
use vars(qw($VERSION));
$VERSION = 1.01;

my $pb = Perlbug::Cmd->new(@ARGV);
$pb->debug(1, "$0: $pb");

# backup db
$pb->debug(1, "TK Interface started...");
my $ok = "boo :-)\n"; # $pb->cmd; # loop
print $ok;
$pb->debug(1, "TK Interface finished...");

$pb->debug(1, "$0 -> $ok");
$pb->clean_up;
exit 0;
