#!/usr/bin/perl 
# Perlbug sqldb datafix updater
# (C) 1999 Richard Foley RFI perlbug@rfi.net 
# $Id: fixit,v 1.1 2000/07/28 06:34:00 perlbug Exp perlbug $
#

=head1 NAME

DATAFIX

=head1 DESCRIPTION

Trawl through the db, looking for incorrect data: correct it, or destroy it :-)

=head1 USAGE

	datafix [object|table]

=cut

use Carp; 
use IO::File;
use File::Spec; 
use lib (File::Spec->updir, qw(/home/richard/Live /home/perlbug));
use Perlbug::Fix;
use strict;
use vars(qw($VERSION));
$|=1;
$VERSION = 1.02;

# DOIT
# -----------------------------------------------------------------------------
my $ok = 1;
my $item  = $ARGV[0] || '';
my $o_fix = Perlbug::Fix->new($item);
$o_fix->cmd; # loop

print "All over -> ok($ok)\n";

exit 0;

