#!/usr/bin/bash

# $Id: install,v 1.1 2000/10/05 13:22:07 perlbug Exp perlbug $

# Installation script for Mysql based Perlbug database

# CREATE
mysql < mysql/create_dbuser.sql;
mysql -u perlbug mysql 	  < mysql/create_database.sql;
mysql -u perlbug -pgublrep < mysql/create_tables.sql;

# SETUP
mysql -u perlbug -pgublrep < generic/insert_admin.sql;
mysql -u perlbug -pgublrep < generic/insert_flags.sql;

# UPDATE
# mysql -u perlbug -pgublrep < Perlbug.sql;
